name: Deploy MultiDocker

on:
  push:
    branches: [ main ]  # change to master if that's your default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # use a Docker Hub access token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Client tests (kept as your current pattern) ---
      - name: Build client test image
        run: docker build -t ${{
          secrets.DOCKERHUB_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - name: Run client tests
        run: docker run --rm -e CI=true ${{
          secrets.DOCKERHUB_USERNAME }}/react-test npm test

      # --- Build & push images ---
      - name: Build & push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push api
        uses: docker/build-push-action@v6
        with:
          context: ./server
          # If your prod Dockerfile is named Dockerfile (not Dockerfile.dev),
          # omit "file:". Add "file: ./server/Dockerfile" if needed.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
