name: Deploy MultiDocker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Client tests (local tag; no push/auth needed) ---
      - name: Build client test image
        run: docker build -t react-test:ci -f ./client/Dockerfile.dev ./client
      - name: Run client tests
        run: docker run --rm -e CI=true react-test:ci npm test

      # --- Build & push images ---
      - name: Build & push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/multi-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/multi-nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push api
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/multi-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/multi-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

